[package]
name = "crypto_files"
version = "0.1.0"
edition = "2024"

[dependencies]
aes = "0.8.4"
cipher = "0.4.4"
config = "0.15.19"
ctr = "0.9.2"
hex = "0.4.3"
rand = "0.9.2"
rang = "0.1.1"
serde = { version = "1.0.219", features = ["derive"] }
uuid = { version = "1", features = ["serde", "v4"] }
